// <auto-generated />
using System;
using MarampaWebApi;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MarampaWebApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210126121555_InitialCreate1")]
    partial class InitialCreate1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("MarampaWebApi.Models.Baptis", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Berkas")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Keterangan")
                        .HasColumnType("longtext");

                    b.Property<string>("NomorSurat")
                        .HasColumnType("longtext");

                    b.Property<string>("Pendeta")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Tanggal")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Tempat")
                        .HasColumnType("longtext");

                    b.Property<bool>("Terverifkasi")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("Updated")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Baptis");
                });

            modelBuilder.Entity("MarampaWebApi.Models.Gereja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Alamat")
                        .HasColumnType("longtext");

                    b.Property<string>("Berkas")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("Klasis")
                        .HasColumnType("longtext");

                    b.Property<string>("Nama")
                        .HasColumnType("longtext");

                    b.Property<string>("Sinode")
                        .HasColumnType("longtext");

                    b.Property<int?>("TahunPelayananId")
                        .HasColumnType("int");

                    b.Property<string>("Telepon")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Updated")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Website")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("TahunPelayananId");

                    b.ToTable("Gereja");
                });

            modelBuilder.Entity("MarampaWebApi.Models.Jemaat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Berkas")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("HubunganKeluarga")
                        .HasColumnType("int");

                    b.Property<int>("JenisKelamin")
                        .HasColumnType("int");

                    b.Property<int?>("KeluargaId")
                        .HasColumnType("int");

                    b.Property<string>("NIK")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("PekerjaanId")
                        .HasColumnType("int");

                    b.Property<int>("StatusJemaat")
                        .HasColumnType("int");

                    b.Property<bool>("StatusPernikahan")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("TanggalLahir")
                        .IsRequired()
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("Updated")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("KeluargaId");

                    b.HasIndex("NIK")
                        .IsUnique()
                        .HasFilter("NIK IS NOT NULL");

                    b.HasIndex("PekerjaanId");

                    b.ToTable("Jemaat");
                });

            modelBuilder.Entity("MarampaWebApi.Models.Keluarga", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Aktif")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Alamat")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Berkas")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NomorKartuKeluarga")
                        .HasColumnType("longtext");

                    b.Property<int>("RayonId")
                        .HasColumnType("int");

                    b.Property<string>("Telepon")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Terdaftar")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("Updated")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("RayonId");

                    b.ToTable("Keluarga");
                });

            modelBuilder.Entity("MarampaWebApi.Models.Meninggal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Berkas")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("JemaatId")
                        .HasColumnType("int");

                    b.Property<string>("Keterangan")
                        .HasColumnType("longtext");

                    b.Property<string>("NomorSurat")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Tanggal")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Tempat")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Updated")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("JemaatId");

                    b.ToTable("Meninggal");
                });

            modelBuilder.Entity("MarampaWebApi.Models.Nikah", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Berkas")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Disini")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Keterangan")
                        .HasColumnType("longtext");

                    b.Property<string>("NomorSurat")
                        .HasColumnType("longtext");

                    b.Property<string>("Pasangan")
                        .HasColumnType("longtext");

                    b.Property<string>("Pendeta")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("TanggalMenikah")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Tempat")
                        .HasColumnType("longtext");

                    b.Property<bool>("Terverifkasi")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("Updated")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Nikah");
                });

            modelBuilder.Entity("MarampaWebApi.Models.Pekerjaan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Berkas")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Deskripsi")
                        .HasColumnType("longtext");

                    b.Property<string>("Nama")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Updated")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Pekerjaan");
                });

            modelBuilder.Entity("MarampaWebApi.Models.Rayon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("BendaharaId")
                        .HasColumnType("int");

                    b.Property<string>("Berkas")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Deskripsi")
                        .HasColumnType("longtext");

                    b.Property<int?>("KetuaId")
                        .HasColumnType("int");

                    b.Property<string>("Nama")
                        .HasColumnType("longtext");

                    b.Property<int?>("SekertarisId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Updated")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("BendaharaId");

                    b.HasIndex("KetuaId");

                    b.HasIndex("SekertarisId");

                    b.ToTable("Rayon");
                });

            modelBuilder.Entity("MarampaWebApi.Models.Sidi", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Keterangan")
                        .HasColumnType("longtext");

                    b.Property<string>("NomorSurat")
                        .HasColumnType("longtext");

                    b.Property<string>("Pendeta")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Tanggal")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Tempat")
                        .HasColumnType("longtext");

                    b.Property<bool>("Terverifkasi")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("Sidi");
                });

            modelBuilder.Entity("MarampaWebApi.Models.TahunPelayanan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Aktif")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Berkas")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("Mulai")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("Sampai")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("Updated")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("TahunPelayanan");
                });

            modelBuilder.Entity("MarampaWebApi.Models.Baptis", b =>
                {
                    b.HasOne("MarampaWebApi.Models.Jemaat", "Jemaat")
                        .WithOne("Baptis")
                        .HasForeignKey("MarampaWebApi.Models.Baptis", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MarampaWebApi.Models.Gereja", b =>
                {
                    b.HasOne("MarampaWebApi.Models.TahunPelayanan", "TahunPelayanan")
                        .WithMany()
                        .HasForeignKey("TahunPelayananId");
                });

            modelBuilder.Entity("MarampaWebApi.Models.Jemaat", b =>
                {
                    b.HasOne("MarampaWebApi.Models.Keluarga", "Keluarga")
                        .WithMany("Jemaat")
                        .HasForeignKey("KeluargaId");

                    b.HasOne("MarampaWebApi.Models.Pekerjaan", "Pekerjaan")
                        .WithMany()
                        .HasForeignKey("PekerjaanId");
                });

            modelBuilder.Entity("MarampaWebApi.Models.Keluarga", b =>
                {
                    b.HasOne("MarampaWebApi.Models.Rayon", "Rayon")
                        .WithMany()
                        .HasForeignKey("RayonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MarampaWebApi.Models.Meninggal", b =>
                {
                    b.HasOne("MarampaWebApi.Models.Jemaat", "Jemaat")
                        .WithMany()
                        .HasForeignKey("JemaatId");
                });

            modelBuilder.Entity("MarampaWebApi.Models.Nikah", b =>
                {
                    b.HasOne("MarampaWebApi.Models.Jemaat", "Jemaat")
                        .WithOne("Nikah")
                        .HasForeignKey("MarampaWebApi.Models.Nikah", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MarampaWebApi.Models.Rayon", b =>
                {
                    b.HasOne("MarampaWebApi.Models.Jemaat", "Bendahara")
                        .WithMany()
                        .HasForeignKey("BendaharaId");

                    b.HasOne("MarampaWebApi.Models.Jemaat", "Ketua")
                        .WithMany()
                        .HasForeignKey("KetuaId");

                    b.HasOne("MarampaWebApi.Models.Jemaat", "Sekertaris")
                        .WithMany()
                        .HasForeignKey("SekertarisId");
                });

            modelBuilder.Entity("MarampaWebApi.Models.Sidi", b =>
                {
                    b.HasOne("MarampaWebApi.Models.Jemaat", "Jemaat")
                        .WithOne("Sidi")
                        .HasForeignKey("MarampaWebApi.Models.Sidi", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
