@controller= https://localhost:5001/api/keluarga
GET {{controller}} HTTP/1.1
Content-Type: application/json

####
GET {{controller}}/2 HTTP/1.1
Content-Type: application/json

####


POST {{controller}} HTTP/1.1
Content-Type: application/json

{
  "nomorKartuKeluarga": "12525252",
  "tanggal": "2021-01-25T14:45:01.552Z",
  "alamat":"jln. Sudirman",
  "jemaat": [{
    "nik": "125252",
    "nama": "Yoseph Kungkung",
    "jenisKelamin": 0,
    "tanggalLahir": "2021-01-25T14:45:01.552Z",
    "hubunganKeluarga": 1,
    "statusJemaat": 0
  }], 
  "rayon":{
    "Id":1,
  "nama": "Wik I",
  "deskripsi": "Wilayah Kali Acai dan sekitar",
  "ketua": null,
  "sekertaris": null,
  "bendahara": null,
  "id": 1,
  "created": "0001-01-01T00:00:00",
  "updated": "2021-01-26T18:22:29.758701",
  "berkas": null
}
}
###


POST {{controller}}/postanggota/2 HTTP/1.1
Content-Type: application/json

{
    "nama": "Aldrich Alpha Jordain",
    "jenisKelamin": 0,
    "tanggalLahir": "2021-01-25T14:45:01.552Z",
    "hubunganKeluarga": 3,
    "statusJemaat": 0
  }

  

####



DELETE  {{controller}}/deleteanggota/2/6 HTTP/1.1
Content-Type: application/json

####